
version: '3.8'
services:
    irede.api:
        image: ${DOCKER_REGISTRY-}iredeapi
        build:
            context: .
            dockerfile: src/irede.api/Dockerfile
        ports: 
            - "8080:8080"
            # - "8081:8081"
        environment:
            - ConnectionStrings__DefaultConnection=Server=irededb;Port=3036;Database=iredeDb;User=root;Password=root;
        depends_on:
            - irededb

    irededb:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: iredeDb
        ports:
            - "3036:3306"
        volumes:
            - db_data:/var/lib/mysql
            - ./init_db:/docker-entrypoint-initdb.d
    
    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 8010:80
        environment:
            - PMA_ARBITRARY=1

volumes:
  db_data:    